// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace StyleCssNamespace {
    export type IStyleCss = any
}

declare const StyleCssModule: StyleCssNamespace.IStyleCss

export = StyleCssModule
