cards = dict(
    {ace_of_spades : 0 } 
    {two_of_spades: 0 }
    {three_of_spades: 0 }
    {four_of_spades: 0 }
    {five_of_spades: 0 }
    {six_of_spades: 0 }
    {seven_of_spades: 0 }
    {eight_of_spades: 0 }
    {nine_of_spades: 0 }
    {ten_of_spades: 0 }
    {jack_of_spades: 0 }
    {queen_of_spades: 0 }
    {king_of_spades: 0 }
    {ace_of_clubs: 0 }
    {two_of_clubs: 0 }
    {three_of_clubs: 0 }
    {four_of_clubs: 0 }
    {five_of_clubs: 0 }
    {six_of_clubs: 0 }
    {seven_of_clubs: 0 }
    {eight_of_clubs: 0 }
    {nine_of_clubs: 0 }
    {ten_of_clubs: 0 }
    {jack_of_clubs: 0 }
    {queen_of_clubs: 0 }
    {king_of_clubs: 0 }
    {ace_of_diamonds: 0 }
    {two_of_diamonds: 0 }
    {three_of_diamonds: 0 }
    {four_of_diamonds: 0 }
    {five_of_diamonds: 0 }
    {six_of_diamonds: 0 }
    {seven_of_diamonds: 0 }
    {eight_of_diamonds: 0 }
    {nine_of_diamonds: 0 }
    {ten_of_diamonds: 0 }
    {jack_of_diamonds: 0 }
    {queen_of_diamonds: 0 }
    {king_of_diamonds: 0 }
    {ace_of_hearts: 0 }
    {two_of_hearts: 0 }
    {three_of_hearts: 0 }
    {four_of_hearts: 0 }
    {five_of_hearts: 0 }
    {six_of_hearts: 0 }
    {seven_of_hearts: 0 }
    {eight_of_hearts: 0 }
    {nine_of_hearts: 0 }
    {ten_of_hearts: 0 }
    {jack_of_hearts: 0 }
    {queen_of_hearts: 0 }
    {king_of_hearts: 0 }
)
